name: algolia
on:
  push:
    paths:
      - 'docs/**/*.md'
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the content of algolia.json as config
        id: algolia_config
        run: echo "config=$(cat docs/algolia.json | jq -r tostring)" >> $GITHUB_OUTPUT
      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env:
          APPLICATION_ID: ${{secrets.ALGOLIA_ACCESS_KEY}}
          ALGOLIA_API_KEY: ${{secrets.ALGOLIA_APPLICATION_ID}}
          CONFIG: ${{ steps.algolia_config.outputs.config }}
